api_platform:
  name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
  defaults:
    normalization_context:
      skip_null_values: false
      extra_properties:
        standard_put: true
  formats:
    jsonld:
      mime_types: [ 'application/ld+json' ]
    json:
      mime_types: [ 'application/json' ]
    html:
      mime_types: [ 'text/html' ]
  keep_legacy_inflector: false
