framework:
    messenger:
        failure_transport: failed

        transports:
            videos:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\Message\ExtractVideoMessage: videos
