vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: '%web.images.users.avatars.url_segment%'
            upload_destination: '%app.filesystem.images.users.avatars.path%'
            namer: App\Vich\Naming\UniqueIDMD5Namer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
