###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        container_name: redis

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        working_dir: /application
        volumes:
            - '.:/application'
            - 'sftube_net-data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sftube_net
            - MYSQL_USER=sftube_net
            - MYSQL_PASSWORD=sftube_net
        ports:
            - '8003:3306'
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1

    elasticsearch:
        image: 'elasticsearch:7.16.3'
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - '9200:9200'
            - '9300:9300'
        volumes:
            - 'sftube_net-elasticsearch-data:/usr/share/elasticsearch/data'

    kibana:
        image: 'kibana:7.16.3'
        container_name: kibana
        ports:
            - '5601:5601'
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - XPACK_SECURITY_ENABLED=false

    webserver:
        image: 'nginx:alpine'
        container_name: nginx
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

    mercure:
      image: dunglas/mercure
      container_name: mercure
      restart: unless-stopped
      environment:
        SERVER_NAME: ':80'
        MERCURE_PUBLISHER_JWT_KEY: '!ChangeMeChangeMeChangeMeChangeMe!'
        MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMeChangeMeChangeMeChangeMe!'
        # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
        MERCURE_EXTRA_DIRECTIVES: |
          cors_origins http://localhost
      # Comment the following line to disable the development mode
      command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
      volumes:
        - mercure_data:/data
        - mercure_config:/config

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password

volumes:
    sftube_net-data:
    sftube_net-elasticsearch-data:
    mercure_data:
    mercure_config:
